### ISSUE TITLE
replace apache reload command failed using nginx

### ISSUE THREAD

**Issue by Arnch** [zend-patterns/ZendServerChefCookbook#22]
Hello,

There is a problem using nginx ,I get the following error : 

```
==> web: NoMethodError
==> web: -------------
==> web: undefined method `log' for Chef::Resource::RubyBlock
==> web: 
==> web: Cookbook Trace:
==> web: ---------------
==> web: /tmp/vagrant-chef/aba213e03e907056b52b53b485f9b906/cookbooks/zendserver/recipes/default.rb:99:in `rescue in block (2 levels) in from_file'
==> web: /tmp/vagrant-chef/aba213e03e907056b52b53b485f9b906/cookbooks/zendserver/recipes/default.rb:95:in `block (2 levels) in from_file'
==> web: 
==> web: 
==> web: Resource Declaration:
==> web: ---------------------
==> web: # In /tmp/vagrant-chef/aba213e03e907056b52b53b485f9b906/cookbooks/zendserver/recipes/default.rb
==> web: 
==> web: 
==> web:  93: ruby_block 'replace apache reload command' do
==> web: 
==> web:  94:   block do
==> web: 
==> web:  95:     begin
==> web:  96:       r = resources('service[apache2]')
==> web:  97:       r.reload_command('/bin/true')
==> web: 
==> web:  98:     rescue Chef::Exceptions::ResourceNotFound
==> web: 
==> web:  99:       log "service[apache2] resource not defined. Skipping restart."
==> web: 
==> web: 100:     end
==> web: 101:   end
==> web: 102: end
```
 
Thanks

**Comment by mkherlakian** [comment]
@Arnch Thanks for opening the issue - I added the block due to a problem with Apache, but omitted to put a guard for Nginx - I will fix shortly. 
Thanks!
